// Casa de Saúde - Database Types

export type AppRole = 'admin' | 'gestor' | 'colaborador_casa_saude' | 'colaborador_unidade_movel' | 'psicologa' | 'visualizador';
export type ConsultaStatus = 'agendada' | 'confirmada' | 'concluida' | 'cancelada' | 'falta' | 'remarcada';
// Mantido por compatibilidade — usar ConsultaTipo para nova lógica
export type ConsultaOrigem = 'casa_saude' | 'unidade_movel';
export type EstadoRegisto = 'ativo' | 'inativo';
export type DocumentoTipo = 'CC' | 'BI';
export type EstadoEntrega = 'ENTREGUE' | 'NAO_ENTREGUE' | 'PENDENTE' | 'CANCELADO' | 'AGUARDAR_VALIDACAO' | 'ERRO_DADOS' | 'EXPIRADO';

export interface Profile {
  id: string;
  email: string;
  nome: string | null;
  avatar_url: string | null;
  ativo: boolean;
  created_at: string;
  updated_at: string;
}

export interface UserRole {
  id: string;
  user_id: string;
  role: AppRole;
  created_at: string;
}

export interface CartaoSaude {
  id: string;
  numero_cartao: string | null;   // generated by DB trigger, never sent on INSERT
  nif: string;                    // UNIQUE, required
  nome_completo: string;
  data_nascimento: string | null;
  tipo_documento: DocumentoTipo | null;
  numero_documento: string | null;
  validade_documento: string | null;
  morada: string | null;
  freguesia: string | null;
  email: string | null;
  telefone: string | null;
  estado_entrega: EstadoEntrega | null;
  created_at: string | null;
  updated_at: string | null;
}

export interface Servico {
  id: string;
  nome: string;
  cor: string | null;
  // ativo is not in the new schema — omit from type
  created_at?: string;
}

export interface Consulta {
  id: string;
  paciente_nif: string;    // NIF do paciente (novo schema)
  servico_id: string;
  data: string;
  hora: string;
  status: ConsultaStatus;
  local: string | null;    // local substitui origem
  notas?: string | null;
  created_at?: string;
  updated_at?: string;
  // Joined
  servicos?: Pick<Servico, 'nome' | 'cor'> | null;
}

// Dropdown options for FuncionarioMT
export const categoriaOptions = [
  'Assistente Operacional',
  'Assistente Técnico',
  'Técnico Superior',
  'Chefe de Divisão',
  'Chefe de Departamento',
  'Chefe de Gabinete',
] as const;

export const divisaoOptions = [
  'Divisão de Recursos Humanos e Apoio à Gestão',
  'Divisão Financeira',
  'Divisão de Educação, Saúde e Ação Social',
  'Divisão de Cultura e Património Cultural',
  'Divisão de Ordenamento e Desenvolvimento Urbano',
  'Divisão de Intervenção no Território e Ambiente',
  'Divisão Economica, Turismo e Património Natural',
] as const;

export const departamentoOptions = [
  'Departamento de Gestão e Desenvolvimento Humano e Social',
  'Departamento de Ambiente, Território, Economia e Patrímonio Natural',
] as const;

export const gabinetesOptions = [
  'Gabinete de Apoio ao Município',
  'Gabinete de Gestão Infantil',
  'Gabinete de Saúde e Ação Social Integrada',
  'Gabinete Juridico e Gestão Património',
  'Gabinete de Inovação, Informação e Comunicação',
  'Gabinete de Apoio às Migrações e Interculturalidade',
  'Gabinete de Gestão de Frotas',
  'Gabinete de Apoio à Presidencia e à Vereação',
] as const;

export const servicosOptions = [
  'Serviçoes Municipais e Proteção Cívil',
  'Serviços Médicos - Veterinário Municipal',
] as const;

export interface FuncionarioMT {
  id: string;
  numero_funcionario: string;
  nome: string;
  telefone: string | null;
  data_nascimento: string | null;
  departamento: string | null;
  categoria: string | null;
  divisao: string | null;
  gabinete: string | null;
  servico: string | null;
  data_admissao: string | null;
  ultimo_exame: string | null;
  estado: string | null;       // 'Ativo' | 'Inativo' — string column in Supabase
  created_at: string;
  updated_at: string;
}

export interface ConsultaMT {
  id: string;
  funcionario_id: string;
  tipo_exame: string;
  data: string;
  hora: string;
  status: ConsultaStatus;
  notas: string | null;
  resultado: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
  // Joined data
  funcionario?: FuncionarioMT;
}

// Flat view of a consulta — used by Consultas.tsx list
export interface ConsultaCSFichaView {
  id: string;              // = consulta.id
  consulta_id: string;
  paciente_nif: string;    // NIF guardado diretamente na consulta
  nome_completo: string | null;  // joined from cartao_saude
  numero_cartao: string | null;  // joined from cartao_saude
  telefone: string | null;       // joined from cartao_saude
  estado_entrega: string | null; // joined from cartao_saude
  data_consulta: string;
  hora_consulta: string;
  status: string;
  local: string | null;
  servico_nome: string | null;
  servico_cor: string | null;
  created_at: string | null;
  updated_at: string | null;
}

export interface CartaoSaudePorNif {
  id: string;
  numero_cartao: string | null;
  nif: string;
  nome_completo: string;
  telefone: string | null;
  estado_entrega: string | null;
}

export interface AuditoriaLog {
  id: string;
  user_id: string | null;
  acao: string;
  entidade: string;
  entidade_id: string | null;
  dados_anteriores: Record<string, unknown> | null;
  dados_novos: Record<string, unknown> | null;
  ip_address: string | null;
  created_at: string;
}

export interface Configuracao {
  id: string;
  chave: string;
  valor: Record<string, unknown> | null;
  descricao: string | null;
  created_at: string;
  updated_at: string;
}

// Status labels and colors
export const statusLabels: Record<ConsultaStatus, string> = {
  agendada: 'Agendada',
  confirmada: 'Confirmada',
  concluida: 'Concluída',
  cancelada: 'Cancelada',
  falta: 'Falta',
  remarcada: 'Remarcada',
};

export const statusColors: Record<ConsultaStatus, string> = {
  agendada: 'badge-agendada',
  confirmada: 'badge-confirmada',
  concluida: 'badge-concluida',
  cancelada: 'badge-cancelada',
  falta: 'badge-falta',
  remarcada: 'badge-remarcada',
};

export const origemLabels: Record<ConsultaOrigem, string> = {
  casa_saude: 'Casa de Saúde',
  unidade_movel: 'Unidade Móvel',
};

export const origemColors: Record<ConsultaOrigem, string> = {
  casa_saude: 'badge-casa-saude',
  unidade_movel: 'badge-unidade-movel',
};

export const estadoLabels: Record<EstadoRegisto, string> = {
  ativo: 'Ativo',
  inativo: 'Inativo',
};

export const estadoColors: Record<EstadoRegisto, string> = {
  ativo: 'badge-ativo',
  inativo: 'badge-inativo',
};

export const documentoTipoLabels: Record<DocumentoTipo, string> = {
  CC: 'Cartão de Cidadão',
  BI: 'Bilhete de Identidade',
};

export const estadoEntregaLabels: Record<EstadoEntrega, string> = {
  ENTREGUE: 'Entregue',
  NAO_ENTREGUE: 'Não Entregue',
  PENDENTE: 'Pendente',
  CANCELADO: 'Cancelado',
  AGUARDAR_VALIDACAO: 'Aguardar Validação',
  ERRO_DADOS: 'Erro nos Dados',
  EXPIRADO: 'Expirado',
};

export const estadoEntregaColors: Record<EstadoEntrega, string> = {
  ENTREGUE: 'badge-concluida',
  NAO_ENTREGUE: 'badge-falta',
  PENDENTE: 'badge-agendada',
  CANCELADO: 'badge-cancelada',
  AGUARDAR_VALIDACAO: 'badge-remarcada',
  ERRO_DADOS: 'badge-falta',
  EXPIRADO: 'badge-falta',
};

// Substitui o que adicionaste no final do ficheiro por isto:

export type ConsultaTipo =
  | 'medicina'
  | 'neurologia'
  | 'psicologia'
  | 'enfermagem'
  | 'unidade_movel';

export interface Psicologa {
  id: string;
  nome: string;
  email: string | null;
  telefone: string | null;
  ativo: boolean;
  created_at: string;
  updated_at: string;
}

export interface Atendimento {
  id: string;
  paciente_nif: string;
  servico_id: string;
  tipo: 'enfermagem' | 'unidade_movel';
  local: string;
  data: string;
  notas: string | null;
  created_by: string | null;
  created_at: string;
  servicos?: Pick<Servico, 'nome' | 'cor'> | null;
}
